### ISSUE TITLE
Error while SoXt configure

### ISSUE THREAD

**Issue by idkakorin** [coin3d/soxt#12]
Hi,

I build the latest version of coin 4.0.1 and installed it and after I tried to build SoXt 1.4.0, but I have met an error while running configure. I found the reason in config.log (lines 936-939), but I can't understand why it happened. My OS is Debian 10. Could you help me, please?
[config.log](https://github.com/coin3d/soxt/files/4865219/config.log)

**Comment by VolkerEnderlein** [comment]
Haven't run configure for a long time, so there may be issues lurking. Can you provide us the exact configure command you are using? You may need to give it a `--with-coin=<coindir>` parameter if Coin is installed in a nonstandard place. 
Another option is to run the CMake commands from the [BuildWithCMake](https://github.com/coin3d/coin/wiki/BuildWithCMake) wiki document to build Coin and SoXt. Please see also the CI build commands for SoXt in https://github.com/coin3d/soxt/blob/master/.github/workflows/continuous-integration-workflow.yml

**Comment by idkakorin** [comment]
I just run configure for SoXt-1.4.0 without any parameters. The problem is in that when I try to build SoXt-1.3.0 everything works well when I do the same.

**Comment by VolkerEnderlein** [comment]
This looks to me like the `coin-config` script cannot find the `coin-default.cfg` for whatever reason. Or the `coin-default.cfg` is not usable. Can you attach those two files? You may need to zip them as only a few file extensions are allowed to upload in Github.

**Comment by idkakorin** [comment]
Done!
[coin.zip](https://github.com/coin3d/soxt/files/4866531/coin.zip)

**Comment by VolkerEnderlein** [comment]
Now things make sense. Did you built Coin with the `CMakeLists.txt` script and try to build SoXt with `configure`? I suspect that from the the broken `coin-default.cfg`. This won't work out. I'm just on the way to fix the pkg-config (*.pc) and the *-default.cfg files. Until that is finished, I strongly encourage you to build both with **either** the `configure` scripts **or** the `CMakeLists.txt` scripts. Both should work on their own as expected.
